// automatically generated by spin2cpp v5.9.14 on Sun Aug 07 14:44:00 2022
// command line: C:\spin2cpp\spin2cpp.exe --p2 -o MaD_Firmware/Librarys/Serial/jm_spi Mad_Firmware/Librarys/Serial/jm_spi.spin2 

#ifndef jm_spi_Class_Defined__
#define jm_spi_Class_Defined__

#include <stdint.h>

class jm_spi {
public:
/*  fixed io pins  */
/*  I  */
// programming / debug
  static const int RX1 = 63;
/*  O  */
  static const int TX1 = 62;
/*  O  */
// serial flash
  static const int SF_CS = 61;
/*  O  */
  static const int SF_SCK = 60;
/*  O  */
  static const int SF_SDO = 59;
/*  I  */
  static const int SF_SDI = 58;
  static const int LSBFIRST = 0;
  static const int MSBFIRST = 1;
  static void 	null(void);
  int32_t 	start(int32_t sdipin, int32_t sdopin, int32_t sckpin, int32_t khz);
  void 	stop(void);
  int32_t 	shiftin(int32_t mode, int32_t bits);
  void 	shiftout(int32_t mode, int32_t value, int32_t bits);
  int32_t 	shiftio(int32_t mode, int32_t outval, int32_t bits);
private:
  volatile int32_t 	setup;
// smart pin #s (-1 if not used)
  volatile int32_t 	sdi;
  volatile int32_t 	sdo;
  volatile int32_t 	sck;
};

#endif
